---
spring:
  application:
    name: device-app
  cloud:
    config:
      enabled: true
      discovery:
        enabled: true

eureka:
  instance:
    nonSecurePort: ${server.port:7080}
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/