spring:
  cloud:
   config:
    server:
      git:
        uri: https://github.com/kvajramani123/MyRepo.git
server:
  port: 9090

eureka:
  instance:
    nonSecurePort: ${server.port:8888}
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

